### ISSUE TITLE
[LE9.1] qBittorrent service fails to start, missing libssl.so.1.0.0

### ISSUE THREAD

**Issue by XxAcielxX** [thoradia/LibreELEC.tv#55]
I was trying to setup qBittorrent on LE9.1 Milhouse latest Builds, but I'm having the following problem. 

```
Mar 12 12:56:19 LibreELEC systemd[1]: Starting qBittorrent service...
Mar 12 12:56:30 LibreELEC sh[787]: qbittorrent-nox: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or dir
Mar 12 12:56:30 LibreELEC systemd[1]: service.qbittorrent.service: Control process exited, code=exited status=127
Mar 12 12:56:30 LibreELEC systemd[1]: service.qbittorrent.service: Failed with result 'exit-code'.
Mar 12 12:56:30 LibreELEC systemd[1]: Failed to start qBittorrent service.
Mar 12 12:56:30 LibreELEC systemd[1]: service.qbittorrent.service: Service RestartSec=100ms expired, scheduling restart.
Mar 12 12:56:30 LibreELEC systemd[1]: service.qbittorrent.service: Scheduled restart job, restart counter is at 5.
Mar 12 12:56:30 LibreELEC systemd[1]: Stopped qBittorrent service.
```

Kindly look into this. Regards~

**Comment by thoradia** [comment]
I have rebuilt the add-ons against LibreELEC master for RPi2 and Generic two days ago
Rebuilt add-ons now use openssl 1.1.1b as do Milhouse builds since 0302

However I have not bumped add-on revision
To use latest add-ons on Milhouse builds: in add-on manager check for updates then update add-ons manually even if add-on version is the same

Again: Milhouse builds are alpha releases, expect things to break

**Comment by XxAcielxX** [comment]
Everything works, so you close this now. Thank you
